### ISSUE TITLE
 ImportError: /lib/python3.6/site-packages/cgat/BamTools/bamtools.cpython-36m-x86_64-linux-gnu.so: undefined symbol: bam_read1

### ISSUE THREAD

**Issue by sebastian-luna-valero** [cgat-developers/cgat-apps#43] opened 2019-06-06 21:47 UTC
Hi,

I am trying to make a new release for `cgat-apps` in bioconda where I include `sortedcontainers`, following up with https://github.com/cgat-developers/cgat-apps/issues/42

The updated recipe is in a PR here https://github.com/bioconda/bioconda-recipes/pull/15752

I have now added a new test in the recipe to check for `cgat bam2bed -h` after building the `cgat-apps` package, and I am getting the error message: 
``` ImportError: /lib/python3.6/site-packages/cgat/BamTools/bamtools.cpython-36m-x86_64-linux-gnu.so: undefined symbol: bam_read1```

I have tried a few options to make it work but I don't find a solution and I was wondering whether I could ask @AndreasHeger to have a look.

The issue seems to be when cythonizing `bamtools`. The strange thing is that cython does not give any errors in compilation time, but it fails at runtime. Moreover, it works on our Jenkins instance but it does not work on the bioconda container, and I think the only differences between the two environments are the C/C++ compilers (i.e. pysam, cython, etc. are on the same version)

For our reference, I had a look at:
* http://blog.behnel.de/posts/whats-new-in-cython-029.html
* https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-options
* https://github.com/pandas-dev/pandas/pull/24538/files
* https://github.com/stan-dev/pystan/pull/525/files
* https://stackoverflow.com/questions/34603628/how-to-specify-python-3-source-in-cythons-setup-py

Any ideas?

Best regards,
Sebastian

**Comment by Acribbs** [comment] 2019-06-09 07:30
Hi @sebastian-luna-valero could the last version of cgat-apps be marked as broken as im getting issues with conda installing 0.5.4 and giving `undefined symbol: bam_read1`?

**Comment by sebastian-luna-valero** [comment] 2019-06-09 11:22
I am now asking for help in https://github.com/bioconda/bioconda-recipes/pull/15752

**Comment by AndreasHeger** [comment] 2019-06-10 19:58
Thanks both. Not sure what is happening. I am surprised that `cgat gtf2table` works as it should also import pysam?

**Comment by sebastian-luna-valero** [comment] 2019-06-10 20:06
Thanks, Andreas.

Could you confirm where the "bam_read1" function in `bamtools.pyx` is comming from?

**Comment by AndreasHeger** [comment] 2019-06-10 20:10
This is from htslib. It looks as if the extension arguments in setup.py for GeneModelAnalysis (works) is different for BamTool.bamtools (fails). In the circle CI log this translates to two different commands:

**Comment by AndreasHeger** [comment] 2019-06-10 20:14
Strange

**Comment by AndreasHeger** [comment] 2019-06-10 20:16
I am not set up for testing this, need to install all the cools again.

**Comment by sebastian-luna-valero** [comment] 2019-06-10 20:24
Not sure whether it helps, but this is what I find in `setup.py`:
```
    Extension(
        "cgat.GeneModelAnalysis",
        ["cgat/GeneModelAnalysis.pyx"],
        include_dirs=pysam.get_include() + [numpy.get_include()],
        library_dirs=[],
        libraries=[],
        define_macros=pysam.get_defines(),
        language="c",
    ),
```
vs.
```
    Extension(
        "cgat.BamTools.bamtools",
        ["cgat/BamTools/bamtools.pyx"],
        include_dirs=pysam.get_include() + [numpy.get_include()],
        library_dirs=pysam_libdirs,
        libraries=pysam_libs,
        define_macros=pysam.get_defines(),
        language="c",
        extra_link_args=extra_link_args_pysam,
    ),
```
Is that correct? If not, please tell me and I am happy to patch `setup.py` to check whether it works.

**Comment by AndreasHeger** [comment] 2019-06-10 20:56
Actually, just recalled, GeneModelAnalysis does not use htslib functions directly but only the standard pysam python API functions. So it is correct. 
Trying to set up circle-CI, etc to do local testing.

**Comment by sebastian-luna-valero** [comment] 2019-06-10 20:56
Anything else I could try to help? For example, can I add another test to the recipe to get more info from the bioconda container?

**Comment by sebastian-luna-valero** [comment] 2019-06-10 20:58
Also, can you tell from the logs which `htslib` is being picked up, the stand-alone version of the pysam one?

**Comment by AndreasHeger** [comment] 2019-06-10 21:11
Thanks, unfortunately we can't tell, the only I know way I know about how to debug these things is to use ldd and nm in the environment that fails. You could add `ldd xyz/xyz/bamtools.so`  the tests, but getting the path right might need some experimenting.

**Comment by AndreasHeger** [comment] 2019-06-10 21:11
It is probably about the compiler being used as you expect.

**Comment by sebastian-luna-valero** [comment] 2019-06-10 21:13
Thanks.

Currently in the bioconda recipe we have the test section like this:
```
test:
    - cgat --help
    - cgat --help Conversion
    - cgat gtf2table -h
    - cgat bam2bed -h
```

Could you remind me of a different cgat tool that we can test to double check the issue, please?

**Comment by sebastian-luna-valero** [comment] 2019-06-10 21:20
Also, I remember I used:
```
export CFLAGS="-I$PREFIX/include -DHAVE_LIBDEFLATE"
export CPPFLAGS="-I$PREFIX/include -DHAVE_LIBDEFLATE"

export HTSLIB_LIBRARY_DIR=$PREFIX/lib
export HTSLIB_INCLUDE_DIR=$PREFIX/include
```
in the `build.sh` of the bioconda recipe. Do you think we need to keep this? or is it no longer needed?

FYI:
http://pysam.readthedocs.org/en/latest/installation.html#external

**Comment by AndreasHeger** [comment] 2019-06-11 20:53
Hi Sebastian, I am not sure, but I hoped that this can be taken care of setup.py querying pysam.get_includes(), etc.

**Comment by AndreasHeger** [comment] 2019-06-11 20:54
I had no luck with the circle ci build, but I can reproduce the problem locally with bioconda-utils.

**Comment by AndreasHeger** [comment] 2019-06-11 20:57
bam2stats is another tool that would cause issues.

**Comment by AndreasHeger** [comment] 2019-06-13 20:41
I have added a `[hts]` to the libraries to be linked against.

**Comment by AndreasHeger** [comment] 2019-06-13 20:42
See #44

**Comment by Charlie-George** [comment] 2019-09-25 13:07
This still seems to be a problem - 

`conda install -c conda-forge -c bioconda cgat-apps` installs cgat-apps 5.5  


`(test_cgat_apps) [charlotteg@cgath1 cloneseq]$ python
Python 3.7.1 (default, Oct 23 2018, 19:19:42) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cgat.BamTools.bamtools import bam2stats_count
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cgat.BamTools.bamtools'` 

or

**Comment by sebastian-luna-valero** [comment] 2019-09-26 16:03
Hi Charlie,

Strange, I have just installed cgat-apps 0.5.5 and that import works for me.

Could you please copy and paste the output of:
```
which cgat
which conda
conda list
```

Best regards,
Sebastian

**Comment by paulbrodersen** [comment] 2019-09-27 09:19
Hi Sebastian,

I am Paul, a new member in David Sims group, and it's actually me that is having the issue. 
Charlie was kindly helping me debug and in the process raised the issue. 

To answer your questions:
```
which cgat
# /ifs/devel/paulb/miniconda3/envs/cloneseq/bin/cgat
which conda
# /ifs/devel/paulb/miniconda3/condabin/conda
```

The output of `conda list` is [here.](https://github.com/cgat-developers/cgat-apps/files/3661876/conda_list_cloneseq.txt)

To setup this conda environment, I used the the environment yaml file that is being used for teaching the cgat course as a base and added a few dependencies that seemed to be missing, specifically `bwa`, `bamtools`, and `cgat-apps`. The latest version of `cgat-apps` was installed. 

Other things that I have tried since:
1. Downgrading to `cgat-apps` 0.5.4: same issue.
2. Downgrading to `cgat-apps` 0.5.3: different issue, but maybe less interesting as I doubt that you will want to roll back that far. 
3. Replacing `cgat-apps` 0.5.5 downloaded from bioconda with the version from github with 
```
conda remove cgat
cd /my/github/clone/of/cgat-apps
python setup.py develop
```
This fails with compilation errors. 

Thanks for the help, I appreciate it. 
I just got here and trying to understand the pipeline without having used it is a bit daunting,
especially since Charlie and David are teaching a course at the moment and don't have much time to help.  

Best,
Paul

**Comment by Acribbs** [comment] 2019-09-27 09:23
I think the conda environment yaml file may be old. It looks like from the output of `conda list` you have cgat-apps 0.5.4, which was the version where the issue you report happens.

I will be over at the wimm in a few hours if you would like some help. I will try and install a new conda environment for you.

Adam

**Comment by paulbrodersen** [comment] 2019-09-27 10:09
I certainly would appreciate any help I can get. 

Sorry, I posted the results for the original environment that for some reason still downloaded the old version from bioconda. I do have another environment (I have made 4 or 5 by now to find a way around the issue) where `cgat-apps` is of the latest version. That did not solve the issue, as far as I can tell at least.  

```sh
conda list | grep cgat
# cgat                      0.5.5                     dev_0    <develop>
# cgat-apps                 0.5.4            py36h84d0fb7_0    bioconda
# cgatcore                  0.5.15                     py_0    bioconda
```

**Comment by Acribbs** [comment] 2019-09-27 11:58
I will be back over at 2, is that ok?

**Comment by paulbrodersen** [comment] 2019-09-27 12:23
Yeah, that work well for me, thanks!

**Comment by Charlie-George** [comment] 2019-09-27 16:08
@sebastian-luna-valero 

Actually my issue is to do with the channel priorities i think..... 

The import works fine If i do

conda create -n test_env1
conda activate test_env1
conda install cgat-apps

However  if i follow the bioconda instructions that specifies my channel order  the import statement breaks 

conda create -n test_env2
conda activate test_env2
conda install -c conda-forge -c bioconda cgat-apps

by default my channel order is: 

channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch

**Comment by sebastian-luna-valero** [comment] 2019-09-29 20:23
Hi @Charlie-George 

After the following pull requests:
* cgat-core: https://github.com/cgat-developers/cgat-core/pull/80
* cgat-apps: https://github.com/cgat-developers/cgat-apps/pull/35
* cgat-flow: https://github.com/cgat-developers/cgat-flow/pull/105

we changed the conda channel orders from:
* bioconda
* conda-forge
* defaults

to:
* conda-forge
* bioconda
* defaults

However, I did try installing `cgat-apps` with both combinations and it worked for me; Strange!

Have you recently pulled the master branch into your devel folder?

**Comment by Acribbs** [comment] 2020-01-08 15:49
Hi sebastian,

I have cleanly installed cgat-apps into a new environment using the install.sh script and I get the following errors:

```
File "/ifs/devel/adamc/cgat-developers/cgat-apps/cgat/tools/bam2stats.py", line 315, in <module>
    from cgat.BamTools.bamtools import bam2stats_count
ModuleNotFoundError: No module named 'cgat.BamTools.bamtools'
```
Also, tests on master branch are failing and im not sure if this is related to this, probably not since there is output created.

**Comment by sebastian-luna-valero** [comment] 2020-01-09 19:17
Hi Adam,

What command produces that error?

I have just tried a new cgat-apps installation with the install.sh script and it works for me if I do:
```
cgat bam2stats -h
python -c "from cgat.BamTools.bamtools import bam2stats_count"
```

Could you please try a new install and let me know how it goes?

Best regards,
Sebastian

**Comment by Acribbs** [comment] 2020-01-09 19:21
Hi Sebastian,

This was running bam2stats tests (I think the paired one)

Since we have all green again (Thanks for your help) I will re-install and try again. 

BW,
Adam

**Closed** 2020-01-26 20:01 UTC
